import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import SessionProviderWrapper from "@/components/sessionProviderWrapper";
import { auth } from "@/authImport";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {  
  const session = await auth()
  return (
    <html lang="en">
        <SessionProviderWrapper session={session}>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
              <Navbar />
              {children}
            </body>
        </SessionProviderWrapper>
    </html>
  );
}
